### ISSUE TITLE
下载到40M就自动断掉

### ISSUE THREAD

**Issue by huangebai** [razerdp/FriendCircle#24]

**Comment by razerdp** [comment]
@huangebai 稍等，我弄个没有gif预览图的分支

**Comment by razerdp** [comment]
@huangebai 搞定了，master-nopreview分支是没有预览图的，您可以用那个

**Comment by razerdp** [comment]
@huangebai 您可以留下邮箱，我把工程发给你。

**Comment by LuckyJayce** [comment]
你可以专门开一个项目放图片，然后引用地址吧

**Comment by razerdp** [comment]
@LuckyJayce 对喔，好提议-V- 我稍后去做。

**Comment by razerdp** [comment]
@LuckyJayce 项目预览图片已经迁移，感谢您的提议-V-
