### ISSUE TITLE
朋友圈网络出错

### ISSUE THREAD

**Issue by evilchaos** [razerdp/FriendCircle#26]
你好，最近在看你的这个项目，发现网络出错了，显示不了内容了。。。能看看是什么情况么？

**Comment by razerdp** [comment]
@evilchaos 可能那几天阿里在升级服务器。我收到了短信，但没留意。。刚才我刷了一次，没问题

**Comment by peacedt** [comment]
http://120.132.92.21/myserver
这个root地址刷不出来数据.

**Comment by peacedt** [comment]
http://120.26.198.104/myserver
工程里这个root地址是刷不出来数据的

**Comment by dingwanshun** [comment]
@peacedt 怎么才有数据啊

**Comment by razerdp** [comment]
@peacedt @dingwanshun 服务器因为我木有钱续费- -已经关闭了，10月国庆后我会重新打开的。。。

**Comment by songmao123** [comment]
看不到数据呀！服务器还没开吗？:sweat_smile:

**Comment by razerdp** [comment]
@songmao123 抱歉，这个月会重新开的，现在暂时还不行。。。

**Comment by razerdp** [comment]
@songmao123 很高兴，我找到了一个免费的后端云替代方案，叫Bmob的，初步看了一下似乎满足我的需求，我现在开始将数据转移到后端云那里。

**Comment by songmao123** [comment]
@razerdp 好的，谢谢！
