### ISSUE TITLE
您好！服务器端的数据库脚本不完整

### ISSUE THREAD

**Issue by Sabirjan** [razerdp/FriendCircle#27]
服务器端的数据库脚本不完整，配置后找不到一些表
![image](https://cloud.githubusercontent.com/assets/7404699/17929890/11129596-6a36-11e6-8407-0914be7dda82.png)
你 三个月之前发布了项目，但是数据库是6个月前发布的，希望您重新提交一下最新完整的服务器端，谢谢！
如果不方便可以发到我的邮箱:253933559@qq.com
非常感谢！辛苦啦~！

**Comment by razerdp** [comment]
@Sabirjan 国庆之后我会重新启用服务器的-V-
