### ISSUE TITLE
跑不起来  说 

### ISSUE THREAD

**Issue by k354250377** [razerdp/FriendCircle#29]
Error:(35, 13) Failed to resolve: cn.bmob.android:bmob-sdk:3.5.0
<a href="openFile:C:/MyScxbar/FriendCircle/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by razerdp** [comment]
看看工程下的gradle有没有这几句

```xml
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        
        maven { url "https://raw.github.com/bmob/bmob-android-sdk/master" }
    }
}
```


如果有，问题依然在，那么可能需要翻墙来下载依赖包了
