### ISSUE TITLE
图片预览好像没有集成进来

### ISSUE THREAD

**Issue by andy521zhufuli** [razerdp/FriendCircle#30]
你好,您的这个朋友圈的项目, 对于MultiImageMomentsVH中ForceClickImageView的点击事件没有处理,简单来说,就是图片缩放的功能没有哦

**Comment by razerdp** [comment]
@andy521zhufuli 目前来说是的，因为这个项目目前是处于重构版本，而在此之前的版本是实现了这些功能的，但由于阿里云服务器太贵，承担不起，所以打算换一个服务器并且把整个项目重构。每一次改动都会有进度记录的，详情在这里：
https://github.com/razerdp/FriendCircle/blob/master/UPDATE_LOG.md

下一阶段做的是评论框定位到动态或者评论，然后才开始着手图片的点击事件。
我会尽快完成赶上重构之前的版本进度的~谢谢支持。

**Comment by andy521zhufuli** [comment]
可以加你好友吗, 想跟你探讨一下朋友圈图片预览的动画,如何实现.

**Comment by razerdp** [comment]
可以，QQ:  164701463

刚刚解决了点击图片前景色的问题和评论的问题，接下来恰好准备进行图片浏览这部分的工作了

不过如果可以的话，建议您先看看我写过的文章:

[一起撸个微信图片浏览的BaseActivity吧（上）——初步思考与基础结构](http://www.jianshu.com/p/a593acec1470)

[一起撸个微信图片浏览的BaseActivity吧（下）——过渡动画的实现](http://www.jianshu.com/p/2716c08e78b4)

[一起撸个朋友圈吧 - 图片浏览（中）【图片浏览器】](http://www.jianshu.com/p/4c5b5d7dc856)

**Comment by razerdp** [comment]
@andy521zhufuli  您好，我今天增加了动画效果了，，，说实话，其实就是把我文章的最后那个运用到viewpager而已。。。。不过退出动画还没有进行优化，如果您感兴趣，欢迎研究一下哈哈

**Comment by razerdp** [comment]
@andy521zhufuli  退场动画也增加进来了，不过有个问题在于退场后的图片定位似乎有点问题。。。迟点研究一下再解决
