### ISSUE TITLE
您的用户表应该extend BmobUser吧，如果这样可以少写好多代码。是故意的吗？怎么理解，这样有什么好处，求解释。

### ISSUE THREAD

**Issue by lixujiayou** [razerdp/FriendCircle#31]

**Comment by razerdp** [comment]
您好，这个其实不是故意的...这是一个遗留问题- - 我当时阅读文档的时候满脑子想的是怎么弄这些表比较好，然后下意识的想着我需要一个用户表，一个动态表，一个评论表。。。。然而没有留意到bmobuser.....近期会更改回来的~

事实上，等大部分完善之后也许会加上注册登录功能，到时候bmobuser应该会更好，所以迟点我会把数据迁移过去的

**Comment by razerdp** [comment]
今天下午想改的时候，忽然发现如果更改的话，要把表的数据大面积迁移，这样会很麻烦。。。所以最终还是没决定采用bmobuser。。。。目前增加了一个简单版的注册popup,方便测试哦~

**Comment by lixujiayou** [comment]
哎呀，我只是顺口一提，我的app也用的bmob，争取在圣诞节之前更新。感觉您写的代码没三年经验出不来呀，正在学习中。哈哈


在2016年12月14日 17:56，WeiChaoFeng 写道:

今天下午想改的时候，忽然发现如果更改的话，要把表的数据大面积迁移，这样会很麻烦。。。所以最终还是没决定采用bmobuser。。。。目前增加了一个简单版的注册popup,方便测试哦~

**Comment by razerdp** [comment]
哈哈，其实。。。我毕业还不够一年-V- 工作经验的话刚好一年的样子吧~所以其实还有很大优化的地方的，，，不过不急，慢慢成长咯

**Comment by lixujiayou** [comment]
我也是刚工作一年，这样一说我已经.....oh no抓紧学习啦。
