### ISSUE TITLE
下拉刷新的时候，有时点赞和评论不能全部显示。

### ISSUE THREAD

**Issue by lixujiayou** [razerdp/FriendCircle#38]
下拉刷新的时候，有时点赞和评论不能全部显示，不知道您发现了没，是哪里的问题呢

**Comment by razerdp** [comment]
我注意到了，迟点我检查一下

**Comment by razerdp** [comment]
debug了一下，似乎是bmob的问题，因为打印了rx的error，而我的项目是没有用到rx的，bmob内部封了rx，所以应该是bmob的问题，说实话，我现在采取朋友圈数据拉取的方式很粗暴，但又没办法，只能说希望bmob可以更新一下接口，尽快可以做到一次性把关联表查完并返回吧

**Comment by razerdp** [comment]
@lixujiayou 已经修复了，这次我重构了bmob后台的表，拉取动态信息不再会有大量的重复请求，所以这次应该不会再出现那种奇怪的情况了
