### ISSUE TITLE
图片九宫格

### ISSUE THREAD

**Issue by 523931340** [razerdp/FriendCircle#39]
点击九宫格空白地方会响应到图片的点击事件

**Comment by razerdp** [comment]
是单张图片还是多张？

**Comment by 523931340** [comment]
都存在,先点开带空格的PhotoContent控件中的任意图片,再点击PhotoContent空白地方

**Comment by razerdp** [comment]
好的，我验证了一下，确实有这个问题，周末我研究一下。（初步判定是状态没被我清除的问题），PhotoContent这个控件在我的另一个仓库里：https://github.com/razerdp/PhotoContents  您也可以去看看源码一起研究一下

**Comment by razerdp** [comment]
@523931340 

你好，这个问题我已经定位了。

具体是PhotoContents控件中，我写touch事件的时候在判断到点击非法位置的时候忘记重置上一次的点击位置了。

具体代码在：[PhotoContents.java](https://github.com/razerdp/PhotoContents/blob/master/lib/src/main/java/razerdp/github/com/widget/PhotoContents.java)的`onTouchDown()`(355行开始).....

源代码：
```java
          if (checkPositionValided(selectionPosition)) {
                View view = getChildAt(selectionPosition);
                if (view != null && view.isEnabled()) {
                    updateChildPressState(selectionPosition, true);
                    this.mSelectedPosition = selectionPosition;
                } 
            }
        } 
```

这里是判断点击的位置是否在content中的imageview，当不符合的时候没有做处理，导致了上一次点击的位置仍然被记录着，现在加了这边的逻辑。应该被修复了。

谢谢你的反馈-V-
