### ISSUE TITLE
BaseRecyclerViewAdapter类里面notifyItemRemoved没有自动更新adapter的position，需要再调用notifyItemRangeChanged(0,datas.size()) 方法更新position

### ISSUE THREAD

**Issue by 112721933** [razerdp/FriendCircle#43]
BaseRecyclerViewAdapter类里面notifyItemRemoved没有自动更新adapter的position，需要再调用notifyItemRangeChanged(0,datas.size()) 方法更新position

**Comment by razerdp** [comment]
你好，具体实现其实是CircleRecyclerView的`InnerWrapperHeaderViewRecyclerAdapter`里，这里对传入的adapter是再包了一层adapter代理的。 可能问题出现在这里，具体原因我还没debug，检查到了我再在这里回复您

**Comment by 112721933** [comment]
谢谢，现在正在看你这个项目，感觉要学的多啊

**Comment by razerdp** [comment]
一起进步-V-

**Comment by razerdp** [comment]
@112721933 我自己尝试了一下remove，似乎没有你所说的问题哦

**Comment by razerdp** [comment]
有一点值得注意的是，baseadapter里面是自己有个数组维持的，也就说adapter里面的数组和外面传进来的并不是同一个对象，所以如果外面remove，表现出来里面的adapter也许是并没有对应的动作的（详见构造器）
