### ISSUE TITLE
有可能会获取不到itemView，特别是当view没有完全visible的时候

### ISSUE THREAD

**Issue by ppg408331701** [razerdp/FriendCircle#54]
对齐评论框的功能现在有办法解决了吗?

我仔细看了微信,我发现微信的实现方式是软键盘弹出后,recyclerview才开始移动的

但是我还是没办法做出了

**Comment by razerdp** [comment]
这个暂时没办法解决，因为recyclerview在没有完全visible时确实会存在没法拿到ItemView的情况。。。

这个在FriendCircleDemoActivity里我也注明了：具体方法是：alignCommentBoxToView()，暂时没有好的解决方法。。。如果你有好的解决方案请告诉我一下，谢谢。

**Comment by razerdp** [comment]
已经解决
