### ISSUE TITLE
关于recycleview嵌套gridview的问题

### ISSUE THREAD

**Issue by songsongtao** [razerdp/FriendCircle#60]
我写的刚好也是你的这种九宫格列表方式，但是在滑动切换的时候因为setNumColumns和刷新gridview数据
当图片个数不一样时会有卡顿，我是根据屏幕均分的

**Comment by songsongtao** [comment]
//九宫格GridView
            final GridView gridView = helper.getView(R.id.gv);
            //复用adapter
            BlogGridAdapter adapter = (BlogGridAdapter) gridView.getAdapter();
            if (images == null || images.size() == 0) {//没有图片数据隐藏起来
                if (adapter == null) {
                    adapter = new BlogGridAdapter(null, mContext);
                    gridView.setAdapter(adapter);
                } else {
                    adapter.resetDataView(null);
                }
                return;
            }

            if (images.size() >= 3) {//根据个数设置几行
                gridView.setNumColumns(3);
            } else if (images.size() == 2) {
                gridView.setNumColumns(2);
            } else {
                gridView.setNumColumns(1);
            }

            gridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    String url = images.get(position);
                    if (TextUtils.isEmpty(url)) {
                        return;
                    }

                    Intent start = PicDetailActivity.start(gridView.getContext(), images, position);
                    if (Build.VERSION.SDK_INT >= 21) {

                        view.findViewById(R.id.iv_pic).setTransitionName("photo");

                        ActivityOptionsCompat options = ActivityOptionsCompat.
                                makeSceneTransitionAnimation(activity, view.findViewById(R.id.iv_pic), "photo");
                        activity.startActivity(start, options.toBundle());
                    } else {
                        activity.startActivity(start);
                    }
                }
            });

            if (adapter == null) {
                adapter = new BlogGridAdapter(images, gridView.getContext());
                gridView.setAdapter(adapter);
            } else {
                adapter.resetDataView(images);
            }

**Comment by songsongtao** [comment]
//九宫格GridView
            final GridView gridView = helper.getView(R.id.gv);
            //复用adapter
            BlogGridAdapter adapter = (BlogGridAdapter) gridView.getAdapter();
            if (images == null || images.size() == 0) {//没有图片数据隐藏起来
                if (adapter == null) {
                    adapter = new BlogGridAdapter(null, mContext);
                    gridView.setAdapter(adapter);
                } else {
                    adapter.resetDataView(null);
                }
                return;
            }

            if (images.size() >= 3) {//根据个数设置几行
                gridView.setNumColumns(3);
            } else if (images.size() == 2) {
                gridView.setNumColumns(2);
            } else {
                gridView.setNumColumns(1);
            }

            gridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    String url = images.get(position);
                    if (TextUtils.isEmpty(url)) {
                        return;
                    }

                    Intent start = PicDetailActivity.start(gridView.getContext(), images, position);
                    if (Build.VERSION.SDK_INT >= 21) {

                        view.findViewById(R.id.iv_pic).setTransitionName("photo");

                        ActivityOptionsCompat options = ActivityOptionsCompat.
                                makeSceneTransitionAnimation(activity, view.findViewById(R.id.iv_pic), "photo");
                        activity.startActivity(start, options.toBundle());
                    } else {
                        activity.startActivity(start);
                    }
                }
            });

            if (adapter == null) {
                adapter = new BlogGridAdapter(images, gridView.getContext());
                gridView.setAdapter(adapter);
            } else {
                adapter.resetDataView(images);
            }

**Comment by razerdp** [comment]
@songsongtao 

您好，在重构之前我是用gridview，但重构之后抛弃了这种adapterview的嵌套，改为自定义控件了。。。

用的是我写的另一个库

https://github.com/razerdp/PhotoContents

也是adapter模式，但继承flowlayout并做了二次缓存的。

当初选定方案也曾试过用gridview，但因为种种原因（也有你所说到的列数问题，最终抛弃这个想法）

这是我的重构过程和思路：

https://www.jianshu.com/p/547b24cfad76

感谢您的代码和idea

**Comment by songsongtao** [comment]
gridview,显示一行问题，焦点滑动，setNumColumns卡顿我也是无语了

**Comment by razerdp** [comment]
应该是频繁requestLayout导致measure的问题
