### ISSUE TITLE
发现个bug

### ISSUE THREAD

**Issue by ouluqiang** [razerdp/FriendCircle#62]
选多个图片发布的时候，不能移除图片

**Comment by razerdp** [comment]
谢谢你的反馈，，，这个问题产生的原因是：

因为还没做（主要是取消选择后没有进行数据的remove操作）

。。。暂时没空做TAT，你可以到

https://github.com/razerdp/FriendCircle/issues/61

写一个todo，我会根据列表来进行下一步的代码迭代的
