### ISSUE TITLE
回复别人的问题

### ISSUE THREAD

**Issue by AngelBo** [razerdp/FriendCircle#64]
你好 请问为什么回复别人的时候 没有显示谁回复了谁呢 就直接显示内容了

**Comment by razerdp** [comment]
@AngelBo 已经更新解决这个问题了

**Comment by nieshiming** [comment]
> @AngelBo 已经更新解决这个问题了

1223

**Comment by yang-shuohao** [comment]
> 你好 请问为什么回复别人的时候 没有显示谁回复了谁呢 就直接显示内容了

哈哈哈
