### ISSUE TITLE
键盘定位到评论的view问题

### ISSUE THREAD

**Issue by cjcj125125** [razerdp/FriendCircle#69]
大佬你好，最近也在做类似于你这个的项目，碰到点问题，当列表很短的时候键盘无法定位到指定的view，另外个问题是我在模拟器上可以让edittextview定位到评论的下方，但是再真机上键盘会挡住edittextview，能否留个qq指点一下(qq 572674557)？？谢谢你

**Comment by razerdp** [comment]
去加群吧，我一般在里面回答的。
