### ISSUE TITLE
点击图片预览闪退

### ISSUE THREAD

**Issue by chenchi0920** [razerdp/FriendCircle#71]
点击图片预览闪退

**Comment by ll354385811** [comment]
8.0以上会出现此问题，将activity theme改成以下 就好了
<style name="Transparent" parent="AppTheme">
        <item name="android:windowBackground">@color/transparent</item>
        <item name="android:windowIsTranslucent">false</item>
        <item name="android:windowDisablePreview">true</item>
    </style>

**Comment by razerdp** [comment]
ya，适配8.0还没有完全去适配。。。。迟点我更新一下
