### ISSUE TITLE
你们这个朋友圈管理员是傻逼吗？

### ISSUE THREAD

**Issue by ningsk** [razerdp/FriendCircle#88]
我根据你们的提示，给了答案，妈的，给老子拒绝了。

**Comment by razerdp** [comment]
答案错误还想进来？就是拒绝这种没耐心的人，谢谢。

**Comment by ningsk** [comment]
去你妈的吧。你告诉我答案是什么？垃圾。做的东西都适配不了机型。我去加你的朋友圈是去讨论问题的。

**Comment by ningsk** [comment]
他妈的，老子在自己的电脑上测试的结果都是对的。

**Comment by razerdp** [comment]
1，一个位运算就是手写也可以算的对你自己弄了个错的答案怪我咯？
2，拒绝了一次就来破口大骂，那更加不能让你进，不欢迎脾气暴躁的人
3，我没说这个朋友圈是个库，适配不适配你的机型关我啥事，这是我练手项目，既然你说项目垃圾那你别关注啊
4，欢迎你出门左转找别的库。
5，本群不欢迎你，再见。
