### ISSUE TITLE
我想看一下后台数据可以吗

### ISSUE THREAD

**Issue by zyyhaizao** [razerdp/FriendCircle#93]
这是我的邮箱1808666464@qq.com

**Comment by razerdp** [comment]
未注册bmob

**Comment by zyyhaizao** [comment]
好了 注册成功了


------------------ 原始邮件 ------------------
发件人: "WeiChaoFeng"<notifications@github.com>;
发送时间: 2019年7月31日(星期三) 上午9:18
收件人: "razerdp/FriendCircle"<FriendCircle@noreply.github.com>;
抄送: "默然"<1808666464@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [razerdp/FriendCircle] 我想看一下后台数据可以吗 (#93)




未注册bmob

**Comment by razerdp** [comment]
加了

**Comment by zyyhaizao** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "WeiChaoFeng"<notifications@github.com>;
发送时间: 2019年7月31日(星期三) 上午9:37
收件人: "razerdp/FriendCircle"<FriendCircle@noreply.github.com>;
抄送: "默然"<1808666464@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [razerdp/FriendCircle] 我想看一下后台数据可以吗 (#93)




加了
